### POST - 채팅방 생성
POST {{root-path}}/api/chat_rooms
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}

{
  "reservationId": 1
}

### POST - 채팅방 생성
POST {{root-path}}/api/chatrooms
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}

{
  "reservationId": 2
}

### GET - 채팅방 목록 조회
GET {{root-path}}/api/chat_rooms
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}

### GET - 알림 내역 조회
GET {{root-path}}/sse/notifications
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}