### POST - 예약 생성
POST {{root-path}}/api/reservations
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}

{
  "mentor": 7,
  "ticket": 2,
  "reservationStatus": "PAID",
  "reservationStartAt": "2025-06-24 12:49:00",
  "reservationEndAt": "2025-06-24 13:09:00"
}
