name: deploy.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: Debug paths in GitHub Actions
        run: |
          echo "Checking paths to be copied"
          ls -la ./build/libs
          ls -la ./

      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
        # secrets에 정의된 값을 사용하여 .env 파일을 생성
      - name: Copy all docker-related files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 서버 접속 SSH Private Key
          port: 22
          source: '.env,./docker-compose.yml,./Dockerfile,./build/libs/*.jar'
          target: "~/Nest.dev"

      - name: SSH and deploy via docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/Nest.dev
            
            docker-compose down || true
            
            docker-compose up --build -d
            
            docker-compose logs --tail=30



